spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DB_NAME}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: ture
        dialect:

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-uri: ${KAKAO_REDIRECT_URI}
    client-secret: ${KAKAO_CLIENT_SECRET}
    scope:
      - profile_nickname
      - account_email
  naver:
    client-id: ${NAVER_CLIENT_ID}
    redirect-uri: ${NAVER_REDIRECT_URI}
    client-secret: ${NAVER_CLIENT_SECRET}
    state: ${NAVER_STATE}
    scope:
      - name
      - email

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: ${SWAGGER_PATH}
    disable-swagger-default-url: true
    display-request-duration: true
  paths-to-match: /**